version: '3.9'
networks:
  restaurant:
    name: restaurant

services:
  api:
    image : api
    container_name: api
    build:
      context: ./
      dockerfile: ./docker/api.dockerfile
      target: dev
    ports:
      - "3000:3000"
    working_dir: /var/www
    volumes:
      - ./:/var/www
    environment:
      PORT: 3000
      MONGODB_URI: mongodb://mongodb:27017
      DB_NAME: sample-db
      NODE_ENV: dev
    depends_on: 
      - mongo
    networks:
      - restaurant

  test:
    tty: true
    image : test
    container_name: test
    build:
      context: ./
      dockerfile: ./docker/api.dockerfile
      target: test
    working_dir: /var/www
    volumes:
      - ./:/var/www
    environment:
      MONGODB_URI: mongodb://mongodb:27017
      DB_NAME: sample-test-db
      NODE_ENV: test
    depends_on: 
      - mongo
    networks:
      - restaurant

  consumers:
    tty: true
    image : consumers
    container_name: consumers
    build:
      context: ./
      dockerfile: ./docker/api.dockerfile
      target: consumers
    working_dir: /var/www
    volumes:
      - ./:/var/www
    environment:
      MONGODB_URI: mongodb://mongodb:27017
      DB_NAME: sample-db
      NODE_ENV: consumers
    depends_on: 
      - mongo
    networks:
      - restaurant

  mongo:
    container_name: mongo
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    restart: always
    volumes:
      - mongodb_data:/data/db
    networks:
      - restaurant

  mongo-express:
    container_name: mongo-express
    image: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
    volumes:
      - mongodb_data:/data/db
    networks:
      - restaurant
    depends_on:
      - mongo

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
        - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
        - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
        - restaurant

volumes:
  mongodb_data: {}